//! ODAMP Risk Sentinel Agent
//!
//! Continuous monitoring of:
//! - Smart contract risk (protocol exploits, audit status)
//! - Liquidity depth (exit time estimation)
//! - Oracle health (Chainlink deviation, staleness)
//! - Protocol TVL changes (sudden drops = red flag)
//! - Geopolitical events affecting holdings
//! - Volatility spikes
//! - Funding rate extremes
//!
//! This agent is ALERT-ONLY. It never executes trades.

use async_trait::async_trait;
use odamp_orchestrator::agent::{Agent, AgentContext, AgentResponse, AgentStatus, ResponseType};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskSentinelConfig {
    pub check_interval_secs: u64,
    pub volatility_alert_pct: f64,
    pub tvl_drop_alert_pct: f64,
    pub oracle_deviation_alert_bps: f64,
    pub funding_rate_extreme: f64,
    pub min_liquidity_usd: f64,
}

impl Default for RiskSentinelConfig {
    fn default() -> Self {
        Self {
            check_interval_secs: 60,
            volatility_alert_pct: 15.0,
            tvl_drop_alert_pct: 20.0,
            oracle_deviation_alert_bps: 50.0,
            funding_rate_extreme: 0.001,
            min_liquidity_usd: 1_000_000.0,
        }
    }
}

/// A risk alert generated by the sentinel.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RiskAlert {
    pub severity: AlertSeverity,
    pub category: RiskCategory,
    pub message: String,
    pub asset: Option<String>,
    pub protocol: Option<String>,
    pub metric: String,
    pub value: f64,
    pub threshold: f64,
    pub recommendation: String,
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum AlertSeverity {
    Info,
    Warning,
    Critical,
    Emergency,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum RiskCategory {
    Volatility,
    Liquidity,
    Oracle,
    ProtocolTvl,
    Geopolitical,
    FundingRate,
    SmartContract,
    Concentration,
}

pub struct RiskSentinelAgent {
    id: uuid::Uuid,
    status: AgentStatus,
    config: RiskSentinelConfig,
    previous_tvl: std::collections::HashMap<String, f64>,
    active_alerts: Vec<RiskAlert>,
}

impl RiskSentinelAgent {
    pub fn new(config: RiskSentinelConfig) -> Self {
        Self {
            id: uuid::Uuid::new_v4(),
            status: AgentStatus::Active,
            config,
            previous_tvl: std::collections::HashMap::new(),
            active_alerts: vec![],
        }
    }

    fn check_volatility(&self, context: &AgentContext) -> Vec<RiskAlert> {
        let mut alerts = vec![];
        let vol_data: std::collections::HashMap<String, f64> = context
            .market_data
            .get("volatility")
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

        for (symbol, vol) in &vol_data {
            if *vol > self.config.volatility_alert_pct {
                alerts.push(RiskAlert {
                    severity: if *vol > self.config.volatility_alert_pct * 2.0 {
                        AlertSeverity::Emergency
                    } else {
                        AlertSeverity::Warning
                    },
                    category: RiskCategory::Volatility,
                    message: format!(
                        "{} volatility at {:.1}% (threshold: {:.1}%)",
                        symbol, vol, self.config.volatility_alert_pct
                    ),
                    asset: Some(symbol.clone()),
                    protocol: None,
                    metric: "realized_vol_24h".into(),
                    value: *vol,
                    threshold: self.config.volatility_alert_pct,
                    recommendation: format!(
                        "Consider reducing exposure to {} or tightening stop-loss.",
                        symbol
                    ),
                    timestamp: chrono::Utc::now(),
                });
            }
        }
        alerts
    }

    fn check_protocol_tvl(&mut self, context: &AgentContext) -> Vec<RiskAlert> {
        let mut alerts = vec![];
        let tvl_data: std::collections::HashMap<String, f64> = context
            .market_data
            .get("protocol_tvl")
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

        for (protocol, tvl) in &tvl_data {
            if let Some(prev) = self.previous_tvl.get(protocol) {
                if *prev > 0.0 {
                    let change_pct = ((*tvl - prev) / prev) * 100.0;
                    if change_pct < -self.config.tvl_drop_alert_pct {
                        alerts.push(RiskAlert {
                            severity: AlertSeverity::Critical,
                            category: RiskCategory::ProtocolTvl,
                            message: format!(
                                "{} TVL dropped {:.1}% in last check (${:.0}M → ${:.0}M)",
                                protocol,
                                change_pct.abs(),
                                prev / 1_000_000.0,
                                tvl / 1_000_000.0
                            ),
                            asset: None,
                            protocol: Some(protocol.clone()),
                            metric: "tvl_change_pct".into(),
                            value: change_pct,
                            threshold: -self.config.tvl_drop_alert_pct,
                            recommendation: format!(
                                "Immediate review: {} TVL drop may indicate exploit or mass withdrawal. \
                                 Consider withdrawing positions.",
                                protocol
                            ),
                            timestamp: chrono::Utc::now(),
                        });
                    }
                }
            }
            self.previous_tvl.insert(protocol.clone(), *tvl);
        }
        alerts
    }

    fn check_oracle_health(&self, context: &AgentContext) -> Vec<RiskAlert> {
        let mut alerts = vec![];
        let oracle_data: std::collections::HashMap<String, f64> = context
            .market_data
            .get("oracle_deviation_bps")
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

        for (feed, deviation) in &oracle_data {
            if *deviation > self.config.oracle_deviation_alert_bps {
                alerts.push(RiskAlert {
                    severity: AlertSeverity::Warning,
                    category: RiskCategory::Oracle,
                    message: format!(
                        "Oracle feed {} deviation at {:.0} bps (threshold: {:.0} bps)",
                        feed, deviation, self.config.oracle_deviation_alert_bps
                    ),
                    asset: Some(feed.clone()),
                    protocol: Some("chainlink".into()),
                    metric: "deviation_bps".into(),
                    value: *deviation,
                    threshold: self.config.oracle_deviation_alert_bps,
                    recommendation: "Oracle deviation may indicate manipulation or data feed issue. \
                                     Avoid executing large orders until resolved.".into(),
                    timestamp: chrono::Utc::now(),
                });
            }
        }
        alerts
    }

    fn check_funding_rates(&self, context: &AgentContext) -> Vec<RiskAlert> {
        let mut alerts = vec![];
        let funding: std::collections::HashMap<String, f64> = context
            .market_data
            .get("funding_rates")
            .and_then(|v| serde_json::from_value(v.clone()).ok())
            .unwrap_or_default();

        for (symbol, rate) in &funding {
            if rate.abs() > self.config.funding_rate_extreme {
                alerts.push(RiskAlert {
                    severity: AlertSeverity::Info,
                    category: RiskCategory::FundingRate,
                    message: format!(
                        "{} funding rate at {:.4}% (extreme: {:.4}%)",
                        symbol, rate * 100.0, self.config.funding_rate_extreme * 100.0
                    ),
                    asset: Some(symbol.clone()),
                    protocol: None,
                    metric: "funding_rate".into(),
                    value: *rate,
                    threshold: self.config.funding_rate_extreme,
                    recommendation: if *rate > 0.0 {
                        "Extremely positive funding: longs are crowded. Short-side opportunity or reduced long risk.".into()
                    } else {
                        "Extremely negative funding: shorts are crowded. Long-side opportunity or reduced short risk.".into()
                    },
                    timestamp: chrono::Utc::now(),
                });
            }
        }
        alerts
    }
}

#[async_trait]
impl Agent for RiskSentinelAgent {
    fn id(&self) -> uuid::Uuid { self.id }
    fn name(&self) -> &str { "RiskSentinel" }
    fn description(&self) -> &str {
        "Continuous monitoring of smart contract risk, liquidity, oracle health, TVL changes, \
         volatility, and geopolitical events. Alert-only — never executes trades."
    }
    fn status(&self) -> &AgentStatus { &self.status }

    async fn on_tick(
        &mut self,
        context: &AgentContext,
    ) -> Result<Option<AgentResponse>, Box<dyn std::error::Error + Send + Sync>> {
        if self.status != AgentStatus::Active || context.kill_switch_active {
            return Ok(None);
        }

        let mut all_alerts = vec![];
        all_alerts.extend(self.check_volatility(context));
        all_alerts.extend(self.check_protocol_tvl(context));
        all_alerts.extend(self.check_oracle_health(context));
        all_alerts.extend(self.check_funding_rates(context));

        // Check for external geopolitical events
        for event in &context.recent_events {
            if let Some(severity) = event.get("severity").and_then(|s| s.as_str()) {
                if severity == "critical" || severity == "emergency" {
                    let desc = event.get("description").and_then(|d| d.as_str()).unwrap_or("Unknown event");
                    all_alerts.push(RiskAlert {
                        severity: AlertSeverity::Emergency,
                        category: RiskCategory::Geopolitical,
                        message: format!("GEOPOLITICAL: {}", desc),
                        asset: None,
                        protocol: None,
                        metric: "geopolitical_event".into(),
                        value: 1.0,
                        threshold: 0.0,
                        recommendation: "Review all positions for geopolitical exposure. \
                                         Consider hedging or reducing cross-border exposure.".into(),
                        timestamp: chrono::Utc::now(),
                    });
                }
            }
        }

        if all_alerts.is_empty() {
            return Ok(None);
        }

        self.active_alerts = all_alerts.clone();

        let highest_severity = all_alerts.iter()
            .map(|a| match a.severity {
                AlertSeverity::Info => 0,
                AlertSeverity::Warning => 1,
                AlertSeverity::Critical => 2,
                AlertSeverity::Emergency => 3,
            })
            .max()
            .unwrap_or(0);

        let message = all_alerts
            .iter()
            .map(|a| format!("[{}] {}", match a.severity {
                AlertSeverity::Info => "INFO",
                AlertSeverity::Warning => "WARN",
                AlertSeverity::Critical => "CRIT",
                AlertSeverity::Emergency => "EMRG",
            }, a.message))
            .collect::<Vec<_>>()
            .join("\n");

        Ok(Some(AgentResponse {
            agent_id: self.id,
            agent_name: self.name().to_string(),
            response_type: ResponseType::Alert,
            message,
            reasoning: format!(
                "Risk scan completed: {} alerts ({} critical/emergency). \
                 Checked: volatility, TVL, oracles, funding, geopolitical.",
                all_alerts.len(),
                all_alerts.iter().filter(|a| {
                    matches!(a.severity, AlertSeverity::Critical | AlertSeverity::Emergency)
                }).count()
            ),
            actions: vec![], // Alert-only agent — no actions
            confidence: 0.98,
            data: Some(serde_json::json!({
                "alerts": all_alerts,
                "highest_severity": highest_severity,
            })),
            timestamp: chrono::Utc::now(),
        }))
    }

    async fn on_query(
        &mut self,
        query: &str,
        _context: &AgentContext,
    ) -> Result<AgentResponse, Box<dyn std::error::Error + Send + Sync>> {
        let lower = query.to_lowercase();

        let message = if lower.contains("risk") || lower.contains("alert") || lower.contains("status") {
            if self.active_alerts.is_empty() {
                "✅ No active risk alerts. All monitored metrics within normal ranges.".to_string()
            } else {
                format!(
                    "⚠️ {} active risk alert(s):\n{}",
                    self.active_alerts.len(),
                    self.active_alerts
                        .iter()
                        .map(|a| format!("  - [{}] {}", a.category, a.message))
                        .collect::<Vec<_>>()
                        .join("\n")
                )
            }
        } else if lower.contains("volatility") {
            "Checking current volatility levels across all positions...".to_string()
        } else if lower.contains("protocol") || lower.contains("tvl") {
            "Checking protocol TVL changes and smart contract risk...".to_string()
        } else {
            format!(
                "I'm the Risk Sentinel agent. I monitor:\n\
                 - Volatility spikes\n\
                 - Protocol TVL drops (exploit detection)\n\
                 - Oracle health (Chainlink deviation)\n\
                 - Funding rate extremes\n\
                 - Geopolitical events\n\n\
                 I am alert-only and never execute trades.\n\nYou asked: \"{}\"",
                query
            )
        };

        Ok(AgentResponse {
            agent_id: self.id,
            agent_name: self.name().to_string(),
            response_type: ResponseType::Query,
            message,
            reasoning: "Responded to user risk query.".into(),
            actions: vec![],
            confidence: 0.95,
            data: Some(serde_json::json!({ "active_alerts": self.active_alerts.len() })),
            timestamp: chrono::Utc::now(),
        })
    }

    fn configure(&mut self, params: serde_json::Value) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        if let Some(v) = params.get("volatility_alert_pct").and_then(|v| v.as_f64()) {
            self.config.volatility_alert_pct = v;
        }
        if let Some(v) = params.get("tvl_drop_alert_pct").and_then(|v| v.as_f64()) {
            self.config.tvl_drop_alert_pct = v;
        }
        if let Some(v) = params.get("oracle_deviation_alert_bps").and_then(|v| v.as_f64()) {
            self.config.oracle_deviation_alert_bps = v;
        }
        Ok(())
    }

    fn pause(&mut self) { self.status = AgentStatus::Paused; }
    fn resume(&mut self) { self.status = AgentStatus::Active; }
    fn disable(&mut self, _reason: &str) { self.status = AgentStatus::Disabled; }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn test_volatility_alert() {
        let mut agent = RiskSentinelAgent::new(RiskSentinelConfig::default());

        let mut ctx = AgentContext::new(uuid::Uuid::new_v4());
        ctx.market_data = serde_json::json!({
            "volatility": { "BTC": 25.0, "ETH": 8.0 },
            "protocol_tvl": {},
            "oracle_deviation_bps": {},
            "funding_rates": {},
        });

        let response = agent.on_tick(&ctx).await.unwrap();
        assert!(response.is_some());
        let resp = response.unwrap();
        assert!(resp.message.contains("BTC"));
        assert!(resp.message.contains("25.0%"));
        assert!(!resp.message.contains("ETH")); // below threshold
    }

    #[tokio::test]
    async fn test_tvl_drop_alert() {
        let mut agent = RiskSentinelAgent::new(RiskSentinelConfig::default());

        // First tick: establish baseline
        let mut ctx1 = AgentContext::new(uuid::Uuid::new_v4());
        ctx1.market_data = serde_json::json!({
            "volatility": {},
            "protocol_tvl": { "aave-v3": 5_000_000_000.0 },
            "oracle_deviation_bps": {},
            "funding_rates": {},
        });
        let _ = agent.on_tick(&ctx1).await.unwrap();

        // Second tick: 30% drop
        let mut ctx2 = AgentContext::new(uuid::Uuid::new_v4());
        ctx2.market_data = serde_json::json!({
            "volatility": {},
            "protocol_tvl": { "aave-v3": 3_500_000_000.0 },
            "oracle_deviation_bps": {},
            "funding_rates": {},
        });
        let response = agent.on_tick(&ctx2).await.unwrap();
        assert!(response.is_some());
        assert!(response.unwrap().message.contains("aave-v3"));
        assert!(response.unwrap().message.contains("TVL dropped"));
    }

    #[tokio::test]
    async fn test_no_alerts_normal_conditions() {
        let mut agent = RiskSentinelAgent::new(RiskSentinelConfig::default());

        let mut ctx = AgentContext::new(uuid::Uuid::new_v4());
        ctx.market_data = serde_json::json!({
            "volatility": { "BTC": 5.0, "ETH": 4.0 },
            "protocol_tvl": {},
            "oracle_deviation_bps": { "BTC/USD": 5.0 },
            "funding_rates": { "BTC": 0.0001 },
        });

        let response = agent.on_tick(&ctx).await.unwrap();
        assert!(response.is_none());
    }

    #[tokio::test]
    async fn test_risk_query() {
        let mut agent = RiskSentinelAgent::new(RiskSentinelConfig::default());
        let ctx = AgentContext::new(uuid::Uuid::new_v4());

        let response = agent.on_query("What's my risk status?", &ctx).await.unwrap();
        assert!(response.message.contains("No active risk alerts"));
    }
}   