//! Core strategy trait and types.

use serde::{Deserialize, Serialize};
use async_trait::async_trait;
use crate::error::StrategyError;

/// A trading signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategySignal {
    pub strategy_id: uuid::Uuid,
    pub symbol: String,
    pub action: SignalAction,
    pub amount: f64,
    pub amount_usd: f64,
    pub limit_price: Option<f64>,
    pub reason: String,
    pub confidence: f64, // 0.0 - 1.0
    pub timestamp: chrono::DateTime<chrono::Utc>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum SignalAction {
    Buy,
    Sell,
    Hold,
    Stop,
}

/// Strategy configuration (user-defined parameters).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyConfig {
    pub name: String,
    pub symbols: Vec<String>,
    pub initial_capital_usd: f64,
    pub max_position_usd: f64,
    pub max_daily_spend_usd: f64,
    pub max_drawdown_pct: f64,
    pub stop_loss_pct: f64,
    pub take_profit_pct: Option<f64>,
    pub params: serde_json::Value, // strategy-specific parameters
}

/// Current state of a running strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyState {
    pub id: uuid::Uuid,
    pub status: StrategyStatus,
    pub started_at: chrono::DateTime<chrono::Utc>,
    pub stopped_at: Option<chrono::DateTime<chrono::Utc>>,
    pub total_trades: u32,
    pub total_pnl_usd: f64,
    pub current_drawdown_pct: f64,
    pub daily_spent_usd: f64,
    pub positions: Vec<StrategyPosition>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StrategyPosition {
    pub symbol: String,
    pub amount: f64,
    pub avg_cost: f64,
    pub current_value_usd: f64,
    pub unrealized_pnl_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub enum StrategyStatus {
    Running,
    Paused,
    Stopped,
    Error,
}

/// The core trait all strategies implement.
#[async_trait]
pub trait Strategy: Send + Sync {
    fn id(&self) -> uuid::Uuid;
    fn name(&self) -> &str;
    fn config(&self) -> &StrategyConfig;
    fn state(&self) -> &StrategyState;

    /// Called on each tick (new price data, new block, etc.).
    /// Returns a signal if the strategy decides to act.
    async fn on_tick(&mut self, market_data: &MarketSnapshot) -> Result<Option<StrategySignal>, StrategyError>;

    /// Called when a signal is executed (or rejected).
    async fn on_fill(&mut self, signal: &StrategySignal, filled: bool, fill_price: Option<f64>);

    /// Stops the strategy (e.g., max drawdown hit).
    fn stop(&mut self, reason: &str);

    /// Checks if the strategy should stop due to risk limits.
    fn check_risk_limits(&self) -> Option<String>;
}

/// Snapshot of market data passed to strategies on each tick.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MarketSnapshot {
    pub timestamp: chrono::DateTime<chrono::Utc>,
    pub prices: std::collections::HashMap<String, f64>,
    pub volumes: std::collections::HashMap<String, f64>,
    pub funding_rates: std::collections::HashMap<String, f64>,
    pub volatility: std::collections::HashMap<String, f64>,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_signal_creation() {
        let signal = StrategySignal {
            strategy_id: uuid::Uuid::new_v4(),
            symbol: "BTC".into(),
            action: SignalAction::Buy,
            amount: 0.1,
            amount_usd: 10_000.0,
            limit_price: Some(100_500.0),
            reason: "DCA: scheduled purchase".into(),
            confidence: 0.95,
            timestamp: chrono::Utc::now(),
        };

        assert_eq!(signal.action, SignalAction::Buy);
        assert!(signal.confidence > 0.9);
    }
}   