[package]
name = "odamp-indexer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
hex = { workspace = true }
alloy = { workspace = true }
ethers = { workspace = true }
solana-sdk = { workspace = true }
solana-client = { workspace = true }
futures = { workspace = true }
async-trait = { workspace = true }
reqwest = { workspace = true }
sqlx = { workspace = true }
parking_lot = "0.12"
dashmap = "6"   